pkg: updated kamailio spec file for CentOS
 - updated kamailio spec file for CentOS along with default and init scripts.

diff --git a/pkg/kamailio/rpm/kamailio.init b/pkg/kamailio/rpm/kamailio.init
--- a/pkg/kamailio/rpm/kamailio.init
+++ b/pkg/kamailio/rpm/kamailio.init
@@ -3,7 +3,7 @@
 # Startup script for Kamailio
 #
 # chkconfig: 345 85 15
-# description: Kamailio is a fast SIP Proxy.
+# description: Kamailio is a fast SIP Server.
 #
 # processname: kamailio
 # pidfile: /var/run/kamailio.pid
@@ -12,37 +12,99 @@
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-oser=/usr/sbin/kamailio
-prog=kamailio
+KAM=/usr/sbin/kamailio
+PROG=kamailio
+PID_FILE=/var/run/kamailio.pid
+LOCK_FILE=/var/lock/subsys/kamailio
 RETVAL=0
+DEFAULTS=/etc/default/kamailio
+RUN_KAMAILIO=no
+
+
+# Do not start kamailio if fork=no is set in the config file
+# otherwise the boot process will just stop
+check_fork ()
+{
+    if grep -q "^[[:space:]]*fork[[:space:]]*=[[:space:]]*no.*" /etc/kamailio/kamailio.cfg; then
+        echo "Not starting $DESC: fork=no specified in config file; run /etc/init.d/kamailio debug instead"
+        exit 1
+    fi
+}
+
+check_kamailio_config ()
+{
+        # Check if kamailio configuration is valid before starting the server
+        out=$($KAM -c 2>&1 > /dev/null)
+        retcode=$?
+        if [ "$retcode" != '0' ]; then
+            echo "Not starting $DESC: invalid configuration file!"
+            echo -e "\n$out\n"
+            exit 1
+        fi
+}
+
 
 start() {
-	echo -n $"Starting $prog: "
-	daemon $oser $OPTIONS >/dev/null 2>/dev/null
+	check_kamailio_config
+        if [ "$1" != "debug" ]; then
+            check_fork
+        fi
+	echo -n $"Starting $PROG: "
+	daemon $KAM $OPTIONS >/dev/null 2>/dev/null
 	RETVAL=$?
 	echo
-	[ $RETVAL = 0 ] && touch /var/lock/subsys/kamailio
+	[ $RETVAL = 0 ] && touch $LOCK_FILE
 	return $RETVAL
 }
 
 stop() {
-	echo -n $"Stopping $prog: "
-	killproc $oser
+	echo -n $"Stopping $PROG: "
+	killproc $KAM
 	RETVAL=$?
 	echo
-	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/kamailio /var/run/kamailio.pid
+	[ $RETVAL = 0 ] && rm -f $LOCK_FILE $PID_FILE
 }
+
+# Load startup options if available
+if [ -f $DEFAULTS ]; then
+   . $DEFAULTS || true
+fi
+
+if [ "$RUN_KAMAILIO" != "yes" ]; then
+    echo "Kamailio not yet configured. Edit /etc/default/kamailio first."
+    exit 0
+fi
+
+
+MEMORY=$((`echo $MEMORY | sed -e 's/[^0-9]//g'`))
+[ -z "$USER" ]  && USER=kamailio
+[ -z "$GROUP" ] && GROUP=kamailio
+[ $MEMORY -le 0 ] && MEMORY=32
+
+if test "$DUMP_CORE" = "yes" ; then
+    # set proper ulimit
+    ulimit -c unlimited
+
+    # directory for the core dump files
+    # COREDIR=/home/corefiles
+    # [ -d $COREDIR ] || mkdir $COREDIR
+    # chmod 777 $COREDIR
+    # echo "$COREDIR/core.%e.sig%s.%p" > /proc/sys/kernel/core_pattern
+fi
+
+OPTIONS="-P $PID_FILE -m $MEMORY -u $USER -g $GROUP"
+
 
 # See how we were called.
 case "$1" in
-	start)
+	start|debug)
 		start
 		;;
 	stop)
 		stop
 		;;
 	status)
-		status $oser
+		status $KAM
 		RETVAL=$?
 		;;
 	restart)
@@ -50,13 +112,13 @@ case "$1" in
 		start
 		;;
 	condrestart)
-		if [ -f /var/run/kamailio.pid ] ; then
+		if [ -f $PID_FILE ] ; then
 			stop
 			start
 		fi
 		;;
 	*)
-		echo $"Usage: $prog {start|stop|restart|condrestart|status|help}"
+		echo $"Usage: $PROG {start|stop|restart|condrestart|status|debug|help}"
 		exit 1
 esac
 
