adding debconf question and adding domain and user using ser_ctl

diff --git a/pkg/debian/ser-oob.postinst b/pkg/debian/ser-oob.postinst
--- a/pkg/debian/ser-oob.postinst
+++ b/pkg/debian/ser-oob.postinst
@@ -205,6 +205,26 @@ if [ "$RET" = "true" ] ; then
   /usr/sbin/ser_mysql.sh create -q$PASS
 fi
 
+db_get ser-oob/SERCTL_DOMAIN
+if [ "$RET" != "" ] ; then
+  # clear it, to be sure we do not add it more than once
+  db_set ser-oob/SERCTL_DOMAIN
+  # add the domain using ser_ctl
+  echo "Calling ser_ctl to add domain"
+  ser_ctl add domain $RET || echo "Waring: ser_ctl failed!"
+fi
+
+db_get ser-oob/SERCTL_USER
+if [ "$RET" != "" ] ; then
+  # clear it, to be sure we do not add it more than once
+  db_set ser-oob/SERCTL_USER
+  # add the user using ser_ctl
+  echo "Calling ser_ctl to add user"
+  ser_ctl user add $RET || echo "Waring: ser_ctl failed!"
+  echo "Calling ser_ctl to set user rights"
+  ser_ctl attrs $RET sw_is_admin=1 sw_is_hostmaster=1 || echo "Waring: ser_ctl failed!"
+fi
+
 
 fi # if changing config
 
