- new debian packaging: openser-unixodbc and openser-pa - changelog updated
git-svn-id: https://openser.svn.sourceforge.net/svnroot/openser/trunk@945 689a6050-402a-0410-94f2-e92a70836424

diff --git a/pkg/kamailio/debian/openser.init.in b/pkg/kamailio/debian/openser.init.in
--- a/pkg/kamailio/debian/openser.init.in
+++ b/pkg/kamailio/debian/openser.init.in
@@ -25,7 +25,7 @@ test -f $DAEMON || exit 0
 
 # Load startup options if available
 if [ -f $DEFAULTS ]; then
-   . $DEFAULTS || true
+	. $DEFAULTS || true
 fi
 
 set -e
@@ -36,85 +36,67 @@ MEMORY=$((`echo $MEMORY | sed -e 's/[^0-9]//g'`))
 [ $MEMORY -le 0 ] && MEMORY=32
 
 if test "$DUMP_CORE" = "yes" ; then
-    # Ignore USER and GROUP in this case and use root,
-    # else it won't write the core file.
-    OPTIONS="-P $PIDFILE -m $MEMORY -u root -g root -w $HOMEDIR"
-    ulimit -c unlimited
+	# Ignore USER and GROUP in this case and use root,
+	# else it won't write the core file.
+	OPTIONS="-P $PIDFILE -m $MEMORY -u root -g root -w $HOMEDIR"
+	ulimit -c unlimited
 else
-    OPTIONS="-P $PIDFILE -m $MEMORY -u $USER -g $GROUP"
+	OPTIONS="-P $PIDFILE -m $MEMORY -u $USER -g $GROUP"
 fi
 
 case "$1" in
-  start)
-	# Check if openser configuration is valid before starting the server
-	set +e
-	out=`($DAEMON -c >/dev/null) 2>&1`
-	retcode=$?
-	set -e
-	if [ "$retcode" != '0' ]; then
-	    echo -e "\nThere are errors in the configuration file. Please fix them first."
-	    echo -e "Also make sure you have installed the debian packages that provide"
-	    echo -e "the additional modules that your configuration requires. cpl, jabber,"
-	    echo -e "mysql, postgres and radius are in separate packages."
-	    echo -e "\n$out\n"
-	    exit 0
-	fi
-	echo -n "Starting $DESC: $NAME"
-	start-stop-daemon --start --quiet --pidfile $PIDFILE \
-		--exec $DAEMON -- $OPTIONS || echo -n " already running"
-	echo "."
-	;;
-  stop)
-	echo -n "Stopping $DESC: $NAME"
-	start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE \
-		--exec $DAEMON
-	echo "."
-	;;
-  #reload)
-	#
-	#	If the daemon can reload its config files on the fly
-	#	for example by sending it SIGHUP, do it here.
-	#
-	#	If the daemon responds to changes in its config file
-	#	directly anyway, make this a do-nothing entry.
-	#
-	# echo "Reloading $DESC configuration files."
-	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
-	#	$PIDFILE --exec $DAEMON
-  #;;
-  restart|force-reload)
-	#
-	#	If the "reload" option is implemented, move the "force-reload"
-	#	option to the "reload" entry above. If not, "force-reload" is
-	#	just the same as "restart".
-	#
-	# Check if openser configuration is valid before restarting the server
-	set +e
-	out=`($DAEMON -c >/dev/null) 2>&1`
-	retcode=$?
-	set -e
-	if [ "$retcode" != '0' ]; then
-	    echo -e "\nThere are errors in the configuration file. Please fix them first."
-	    echo -e "Also make sure you have installed the debian packages that provide"
-	    echo -e "the additional modules that your configuration requires. cpl, jabber,"
-	    echo -e "mysql, postgres and radius are in separate packages."
-	    echo -e "\n$out\n"
-	    exit 0
-	fi
-	echo -n "Restarting $DESC: $NAME"
-	start-stop-daemon --oknodo --stop --quiet --pidfile \
-		$PIDFILE --exec $DAEMON
-	sleep 1
-	start-stop-daemon --start --quiet --pidfile \
-		$PIDFILE --exec $DAEMON  -- $OPTIONS
-	echo "."
-	;;
-  *)
+	start)
+		# Check if openser configuration is valid before starting the server
+		set +e
+		out=`($DAEMON -c >/dev/null) 2>&1`
+		retcode=$?
+		set -e
+		if [ "$retcode" != '0' ]; then
+			echo -e "\nThere are errors in the configuration file. Please fix them first."
+			echo -e "Also make sure you have installed the debian packages that provide"
+			echo -e "the additional modules that your configuration requires. cpl, jabber,"
+			echo -e "mysql, postgres and radius are in separate packages."
+			echo -e "\n$out\n"
+			exit 0
+		fi
+		echo -n "Starting $DESC: $NAME"
+		start-stop-daemon --start --quiet --pidfile $PIDFILE \
+			--exec $DAEMON -- $OPTIONS || echo -n " already running"
+		echo "."
+		;;
+	stop)
+		echo -n "Stopping $DESC: $NAME"
+		start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE \
+			--exec $DAEMON
+		echo "."
+		;;
+	restart|force-reload)
+		# Check if openser configuration is valid before restarting the server
+		set +e
+		out=`($DAEMON -c >/dev/null) 2>&1`
+		retcode=$?
+		set -e
+		if [ "$retcode" != '0' ]; then
+			echo -e "\nThere are errors in the configuration file. Please fix them first."
+			echo -e "Also make sure you have installed the debian packages that provide"
+			echo -e "the additional modules that your configuration requires. cpl, jabber,"
+			echo -e "mysql, postgres and radius are in separate packages."
+			echo -e "\n$out\n"
+			exit 0
+		fi
+		echo -n "Restarting $DESC: $NAME"
+		start-stop-daemon --oknodo --stop --quiet --pidfile \
+			$PIDFILE --exec $DAEMON
+		sleep 1
+		start-stop-daemon --start --quiet --pidfile \
+			$PIDFILE --exec $DAEMON  -- $OPTIONS
+		echo "."
+		;;
+	*)
 	N=/etc/init.d/$NAME
-	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N {start|stop|restart|force-reload}" >&2
-	exit 1
-	;;
+		echo "Usage: $N {start|stop|restart|force-reload}" >&2
+		exit 1
+		;;
 esac
 
 exit 0
