- merged from stable (rel0_8_11):       - kill_all_children (fixes 'we kill our launching script bug ')       - debian updates       - tm & sl destroy when not init fixes - ver no. updated

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -26,7 +26,9 @@ set -e
 
 case "$1" in
     configure)
-        adduser --system --group --home /var/run/ser ser
+        adduser --quiet --system --group --disabled-password \
+                --shell /bin/false --gecos "SIP Express Router" \
+                --home /var/run/ser ser || true
 
     ;;
 
@@ -42,12 +44,33 @@ esac
 
 # # dh_installdeb will replace this with shell code automatically
 # # generated by other debhelper scripts.
+# deb_helper is not used here to avoid automatically starting ser after
+# the installation (dh_installinit 4.0 , from woody does not support
+# --nostart, if you're using a newer version is safe to comment out the 
+# rest of the code and add again deb_helper)
 
-# #DEBHELPER#
-echo ""
-echo "Next install any additional ser modules and then (re)start ser"
-echo "by executing command '/etc/init.d/ser start|restart'."
-
+# this will be added automatically by dh_installdocs if deb_helper is 
+# "enabled"
+if [ "$1" = "configure" ]; then
+	if [ -d /usr/doc -a ! -e /usr/doc/ser -a -d /usr/share/doc/ser ]; then
+		ln -sf ../share/doc/ser /usr/doc/ser
+	fi
+fi
+# end dh_installdocs section
+# this will be automativally added by dh_installinit if deb_helper is
+# "enabled
+if [ -x "/etc/init.d/ser" ]; then
+	 update-rc.d ser defaults 23 >/dev/null
+	 if ! invoke-rc.d ser restart ; then
+		echo ""
+		echo "ser failed to (re)start. Perhaps your configuration requires "
+		echo "additional modules (e.g. ser-mysql-module, ser-jabber-module "
+		echo "or ser-radius-modules). Next try to install any additional ser"
+		echo "modules you might need and then (re)start ser by executing "
+		echo "the command '/etc/init.d/ser start|restart'."
+	fi
+fi
+# end dh_installinit section
 
 exit 0
 
