- fix 2.cfg, 7.cfg - contact_avp is not available anymore in lcr - add small function to test for sipsak availability - extend mysql registrar test (11.sh), use sipsak to test for more cases   (cleanup timer in usrloc, unregistration of specific contacts, unregistration   of all contacts, contact binding update..) - extend postgres registrar test (22.sh), use sipsak here too
git-svn-id: https://openser.svn.sourceforge.net/svnroot/openser/trunk@5137 689a6050-402a-0410-94f2-e92a70836424

diff --git a/test/unit/include/require b/test/unit/include/require
--- a/test/unit/include/require
+++ b/test/unit/include/require
@@ -52,3 +52,11 @@ function check_sipp() {
 	fi;
 	return 0
 }
+
+function check_sipsak() {
+	if ! ( which sipsak > /dev/null ); then
+		echo "sipsak not found, not run"
+		return -1
+	fi;
+	return 0
+}
