pkg/kamailio/centos: updates to CentOS 6 build
- Improved startup scripts
- Updated .spec
- README listing and explaining which Kamailio modules are not built for
  CentOS

diff --git a/pkg/kamailio/centos/6/kamailio.init b/pkg/kamailio/centos/6/kamailio.init
--- a/pkg/kamailio/centos/6/kamailio.init
+++ b/pkg/kamailio/centos/6/kamailio.init
@@ -20,49 +20,102 @@
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-kam=/usr/sbin/kamailio
-prog=kamailio
+KAM=/usr/sbin/kamailio
+KAMCFG=/etc/kamailio/kamailio.cfg
+PROG=kamailio
+PID_FILE=/var/run/kamailio.pid
+LOCK_FILE=/var/lock/subsys/kamailio
 RETVAL=0
+DEFAULTS=/etc/sysconfig/kamailio
+RUN_KAMAILIO=no
 
-[ -f /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
+
+# Do not start kamailio if fork=no is set in the config file
+# otherwise the boot process will just stop
+check_fork ()
+{
+    if grep -q "^[[:space:]]*fork[[:space:]]*=[[:space:]]*no.*" $KAMCFG; then
+        echo "Not starting $DESC: fork=no specified in config file; run /etc/init.d/kamailio debug instead"
+        exit 1
+    fi
+}
+
+check_kamailio_config ()
+{
+        # Check if kamailio configuration is valid before starting the server
+        out=$($KAM -c 2>&1 > /dev/null)
+        retcode=$?
+        if [ "$retcode" != '0' ]; then
+            echo "Not starting $DESC: invalid configuration file!"
+            echo -e "\n$out\n"
+            exit 1
+        fi
+}
+
 
 start() {
-	echo -n $"Starting $prog: "
-	# there is something at end of this output which is needed to
-	# report proper [ OK ] status in CentOS scripts
-	daemon $kam $OPTIONS 2>/dev/null | tail -1
+	check_kamailio_config
+        if [ "$1" != "debug" ]; then
+            check_fork
+        fi
+	echo -n $"Starting $PROG: "
+	daemon $KAM $OPTIONS >/dev/null 2>/dev/null
 	RETVAL=$?
 	echo
-	[ $RETVAL = 0 ] && touch /var/lock/subsys/$prog
+	[ $RETVAL = 0 ] && touch $LOCK_FILE && success
+	return $RETVAL
 }
 
 stop() {
-	echo -n $"Stopping $prog: "
-	killproc $kam
+	echo -n $"Stopping $PROG: "
+	killproc $KAM
 	RETVAL=$?
 	echo
-	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/$prog /var/run/$prog.pid
+	[ $RETVAL = 0 ] && rm -f $LOCK_FILE $PID_FILE
 }
 
-MEMORY=$((`echo $MEMORY | sed -e 's/[^0-9]//g'`))
+# Load startup options if available
+if [ -f $DEFAULTS ]; then
+   . $DEFAULTS || true
+fi
+
+if [ "$RUN_KAMAILIO" != "yes" ]; then
+    echo "Kamailio not yet configured. Edit /etc/default/kamailio first."
+    exit 0
+fi
+
+
+SHM_MEMORY=$((`echo $SHM_MEMORY | sed -e 's/[^0-9]//g'`))
 PKG_MEMORY=$((`echo $PKG_MEMORY | sed -e 's/[^0-9]//g'`))
 [ -z "$USER" ]  && USER=kamailio
 [ -z "$GROUP" ] && GROUP=kamailio
-[ $MEMORY -le 0 ] && MEMORY=32
+[ $SHM_MEMORY -le 0 ] && SHM_MEMORY=32
 [ $PKG_MEMORY -le 0 ] && PKG_MEMORY=4
 
-OPTIONS="-P /var/run/$prog.pid -m $MEMORY -M $PKG_MEMORY -u $USER -g $GROUP"
+if test "$DUMP_CORE" = "yes" ; then
+    # set proper ulimit
+    ulimit -c unlimited
+
+    # directory for the core dump files
+    # COREDIR=/home/corefiles
+    # [ -d $COREDIR ] || mkdir $COREDIR
+    # chmod 777 $COREDIR
+    # echo "$COREDIR/core.%e.sig%s.%p" > /proc/sys/kernel/core_pattern
+fi
+
+OPTIONS="-P $PID_FILE -m $SHM_MEMORY -M $PKG_MEMORY -u $USER -g $GROUP $EXTRA_OPTIONS"
+
 
 # See how we were called.
 case "$1" in
-	start)
+	start|debug)
 		start
 		;;
 	stop)
 		stop
 		;;
 	status)
-		status $kam
+		status $KAM
 		RETVAL=$?
 		;;
 	restart)
@@ -70,13 +123,13 @@ case "$1" in
 		start
 		;;
 	condrestart)
-		if [ -f /var/run/$prog.pid ] ; then
+		if [ -f $PID_FILE ] ; then
 			stop
 			start
 		fi
 		;;
 	*)
-		echo $"Usage: $prog {start|stop|reload|restart|condrestart|status|help}"
+		echo $"Usage: $PROG {start|stop|restart|condrestart|status|debug|help}"
 		exit 1
 esac
 
